### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by alexisLefebvre** [loktar00/guihacker#1]
Hello,
the website is unreachable.

**Comment by Unihedro** [comment]
Yes, it is. I'm not surprised though, it was created as a joke and would be amusing if stayed forever. I guess @loktar00 could put it up on Github Project Pages.

**Comment by loktar00** [comment]
Yeah I should add it as a gh-pages branch, or host it on a vps. The site was on my colo server that had a failing drive.. Id bring it up and it would die again. Server is being shipped back to me today actually.

**Comment by loktar00** [comment]
Its back finally, ended up just hosting it on azure.

**Comment by loktar00** [comment]
haha... and its down again, I hate azure's custom domain settings. Fixing it again :/

**Comment by Unihedro** [comment]
Maybe you should use GH pages after all. ;P

**Comment by groe** [comment]
Finally, it's back online and we can all get back to work again!

![hacking](http://i.giphy.com/13AN8X7jBIm15m.gif)

**Comment by alexisLefebvre** [comment]
Thanks, my productivity is increasing again! :+1:
